=== wdhunter645/LGFC-WEBAPP/.astro/collections/settings.schema.json
{
  "$ref": "#/definitions/settings",
  "definitions": {
    "settings": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "contactEmail": {
          "type": "string"
        },
        "socialLinks": {
          "type": "object",
          "properties": {
            "twitter": {
              "type": "string"
            },
            "facebook": {
              "type": "string"
            },
            "instagram": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "description",
        "contactEmail",
        "socialLinks"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== wdhunter645/LGFC-WEBAPP/src/content/settings/site.json
{
  "title": "Lou Gehrig Fan Club",
  "description": "Honoring the legacy of Lou Gehrig and supporting the ALS community",
  "contactEmail": "contact@lougehrigfanclub.com",
  "socialLinks": {
    "twitter": "https://twitter.com/lougehrigfanclub",
    "facebook": "https://facebook.com/lougehrigfanclub",
    "instagram": "https://instagram.com/lougehrigfanclub"
  }
}
